input_owner = "0x1c7b0296b0bf7b61b2dee3ef4afa79e7411d8b32bd3a5c06ca9b2fb5ee1fd6a2"# Public inputs (witnesses to be proven on-chain)

input_asset_id = "0x0000000000000000000000000000000000000000000000000000000000000001"root = "0x1f8e0ab650e5df57432b1b9eaad2daaa4510a91a0b75bd035051d3bcb7c0151d"

input_maturity_date = "1893456000"nullifiers = ["0x1f9622b4d68c1b5b433736ef91c2af7bbff2a6ff7e3de8f7b25f4693493f5df7", "0x2088a1456156a7637b04252cc2cb44e7afec6a73ed8913d1d9166c988fe51948"]

input_value_a = "100"commitments_out = ["0x1156c6bc9367cc966088ceedb112f454eeca564ce36c0af52a1a6dbc8d57162e", "0x1b3df58b47ca4b3e800b6bd238d89a9d78a64245825070dcf50e56f9110a509c"]

input_salt_a = "0x0000000000000000000000000000000000000000000000000000000000000001"

input_private_key_a = "0x0000000000000000000000000000000000000000000000000000000000000999"# Input notes (private)

input_values = [100, 0]

input_value_b = "60"input_salts = [123, 0]

input_salt_b = "0x0000000000000000000000000000000000000000000000000000000000000002"input_owner = "0x1c7b0296b0bf7b61b2dee3ef4afa79e7411d8b32bd3a5c06ca9b2fb5ee1fd6a2"

input_private_key_b = "0x0000000000000000000000000000000000000000000000000000000000001000"input_asset_id = 1

# 2030-01-01 00:00:00 UTC

output_value_a = "60"input_maturity_date = 1893456000

output_salt_a = "0x0000000000000000000000000000000000000000000000000000000000000003"

output_owners = [# Merkle proof paths for each input note

  "0x1c7b0296b0bf7b61b2dee3ef4afa79e7411d8b32bd3a5c06ca9b2fb5ee1fd6a2",path_indices = [[0, 0, 0], [1, 0, 0]]

  "0x1c7b0296b0bf7b61b2dee3ef4afa79e7411d8b32bd3a5c06ca9b2fb5ee1fd6a2"path_elements = [["0x08b7a207093e941afad82cf336de7e3c99fad595b2877316e832b4b2ca3ec723", "0x0", "0x0"], ["0x1de409fb2319657514027650e41731fc3c5b77448fdd2b9aceeda9cf95c499e7", "0x0", "0x0"]]

]

output_value_b = "40"# Output notes (private)

output_salt_b = "0x0000000000000000000000000000000000000000000000000000000000000004"output_values = [40, 60]

output_salts = [456, 789]

# Merkle proof for leaf_a (index 0)output_owners = ["0x1c7b0296b0bf7b61b2dee3ef4afa79e7411d8b32bd3a5c06ca9b2fb5ee1fd6a2", "0x1c7b0296b0bf7b61b2dee3ef4afa79e7411d8b32bd3a5c06ca9b2fb5ee1fd6a2"]

path_elements = [output_asset_ids = [1, 1]

  ["0x08b7a207093e941afad82cf336de7e3c99fad595b2877316e832b4b2ca3ec723", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000"],output_maturity_date = 1893456000

  ["0x1de409fb2319657514027650e41731fc3c5b77448fdd2b9aceeda9cf95c499e7", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000"]

]# Private key

private_key = "999"