# Public inputs (witnesses to be proven on-chain)
root = "0x1759492de3c7754c31e675bb3dfaef1cffdaf938a61b855ded15a318ab2e2ea5"
nullifiers = ["0x6793f2ee8d308faa5e7f710b445274c9afb3e32d374e26a3458881836c0425a", "0x39722ee997387cd3f3dbc711cf2feafe0c381a2a5460643d473a2423f8f16d"]
commitments_out = ["0x19bb2d4dcdd7f41160a8a8ddb0ef0b98cf98194430cf21dbcdc3049f30d90a54", "0x1704129153b6c84b927a0339d5658082f62ec103685fce635e94af14f11b93b8"]

# Input notes (private)
input_values = [100000000, 0]
input_salts = ["0x7e508e9367a2cacb", "0x0"]
input_owner = "0x2f94ae41dc1c9f334fcbfd4eb41d1734f1dcd4edc1df6897faf555ecbd99f4bd"
input_asset_id = 1
input_maturity_date = 1893456000

# Merkle proof paths for each input note
path_indices = [[0, 0, 0], [1, 0, 0]]
path_elements = [["0x183b6ae2947a9621bbf191ed5c8514aa130801ba901fc042ed37115e09bf7453", "0x2098f5fb9e239eab3ceac3f27b81e481dc3124d55ffed523a839ee8446b64864", "0x1069673dcdb12263df301a6ff584a7ec261a44cb9dc68df067a4774460b1f1e1"], ["0x1d7cbf688c284bdbe3fc2b0c052e1e756289d271425dfaa91da2e4acb7407ff1", "0x2098f5fb9e239eab3ceac3f27b81e481dc3124d55ffed523a839ee8446b64864", "0x1069673dcdb12263df301a6ff584a7ec261a44cb9dc68df067a4774460b1f1e1"]]

# Output notes (private)
output_values = [100, 99999900]
output_salts = ["0xb06f630ed5b01a7d", "0x9f790cf919813f5d"]
output_owners = ["0x866b4bd13dd443c81ad69cf31eae5ebd2c487693ed69bc3d7e91f1e214217b6", "0x2f94ae41dc1c9f334fcbfd4eb41d1734f1dcd4edc1df6897faf555ecbd99f4bd"]
output_asset_ids = [1, 1]
output_maturity_date = 1893456000

# Private key
private_key = "0x234808e5dd759477"
